# Generated by Django 5.0.4 on 2024-05-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0002_team_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_owner',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
