# Generated by Django 5.0.4 on 2024-05-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0006_room_team_a_players_room_team_b_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='players',
        ),
    ]
