# Generated by Django 5.0.4 on 2024-05-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0007_remove_room_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seed',
            field=models.IntegerField(default=11111),
        ),
    ]
