# Generated by Django 5.0.4 on 2024-05-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0008_room_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='shuftler',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
