# Generated by Django 5.0.4 on 2024-05-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0009_room_shuftler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='shuftler',
            new_name='shuffler',
        ),
    ]
