# Generated by Django 5.0.4 on 2024-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0010_rename_shuftler_room_shuffler'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seeds',
            field=models.TextField(default='[]'),
        ),
    ]
