# Generated by Django 5.0.4 on 2024-05-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0012_remove_room_seed_room_card_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bidder_index',
            field=models.IntegerField(default=1),
        ),
    ]
