# Generated by Django 5.0.4 on 2024-05-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0013_room_bidder_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='card_indices',
            field=models.TextField(default=''),
        ),
    ]
