# Generated by Django 5.0.4 on 2024-05-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0014_alter_room_card_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bid_chalenger_index',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='bid_value',
            field=models.IntegerField(default=16),
        ),
    ]
