# Generated by Django 5.0.4 on 2024-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0015_room_bid_chalenger_index_room_bid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='trump_selecter_index',
            field=models.IntegerField(default=0),
        ),
    ]
