# Generated by Django 5.0.4 on 2024-05-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0016_room_trump_selecter_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bid_chalenger_index',
            new_name='bid_challenger_index',
        ),
    ]
