# Generated by Django 5.0.4 on 2024-05-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0019_rename_trump_selecter_index_room_team_a_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='trump',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
