# Generated by Django 5.0.4 on 2024-05-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0020_room_trump'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bid_last_pass',
            field=models.BooleanField(default=False),
        ),
    ]
