# Generated by Django 5.0.4 on 2024-05-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0021_room_bid_last_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='curr_player',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='round_player',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
