# Generated by Django 5.0.4 on 2024-05-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_28', '0022_room_curr_player_room_round_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='curr_player',
        ),
        migrations.RemoveField(
            model_name='room',
            name='round_player',
        ),
        migrations.AddField(
            model_name='room',
            name='card_played',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='room',
            name='curr_player_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='round_player_index',
            field=models.IntegerField(default=0),
        ),
    ]
